name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi welsome to issues before creating your first issue please refer to the readme file '' first issue'
        pr-message: 'Thanks for submitting a PR the code mantainers will soon review this and if this is upto the mark it will be merged '' first pr'
